(add-to-list 'load-path "~/.emacs.d/lisp/")

(require 'init-default)
(require 'init-packages)
(require 'init-env)
(require 'init-evil)
(require 'init-complete)
(require 'init-helper)
(require 'init-dired)
(require 'init-search)
(require 'init-diff)
(require 'init-ui)
(require 'init-term)
(require 'init-python)
